# Site settings
title: I LOVE PINKIE # 你的博客名字，可以定义修订
header-img: <img src="http://q7hawnr2l.bkt.clouddn.com/984495.png" />
tagline: "cn"  
description: "凤歌笑孔丘"  # 一句话描述你的博客
baseurl: ""
url: "http://sranderson.pw"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "SRANDERSON" # 填写作者信息：名字
  email: 3185858940wjz@gmail.com # 填写作者信息：邮箱
  bio: "凤歌笑孔丘" # 填写作者信息：博客描述

# Data
gavatar: img/SR.png # 浏览器地址栏小图标，可自定义更改
favicon: img/SR.png # 浏览器地址栏小图标，可自定义更改

douban_username: "182677644/"
twitter_username: "@XL2Ibqt2l7wifBi"
github_username: "SR-AndersoN" 
facebook_username: "苏格拉底"
weibo_username: "苏格拉底"
zhihu_username: "su-ge-la-di-22-19"

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "SRANDERSON" # 你的名字
      header-img: "img/headpageA2.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name : "SR Anderson" # 填写你的 disqus id
  disqus :
      short_name : "SR Anderson"  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: "SRANDERSON" # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

theme: jekyll-theme-merlot
